apiVersion: apps/v1
kind: Deployment
metadata:
  name: avn-cart-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-app
  template:
    metadata:
      labels:
        app: cart-app
    spec:
      containers:
        - name: cart-app-cntnr
          image: 577054949759.dkr.ecr.eu-west-2.amazonaws.com/avn-repo:cartapp
          ports:
            - containerPort: 8091

---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-app
  ports:
    - port: 80
      targetPort: 8091
      #protocol: TCP
  type: ClusterIP